import landingPage from "../pageObjects/landingPage.cy";
import commonFunction from '../pageObjects/commonFunction.cy'
import assessmentPage from "../pageObjects/assessmentPage.cy";


describe('validating Quality Assurance Module', () => {
  beforeEach('User should get navigated to Okta by launching the url', () => {
    cy.visit('/')
    cy.wait(500)
  })

  //Architectural style parameter
  it('tc001 Build In Quality Mindset topic validation', () => {
    landingPage.assessmentNameInGrid(1).click()
    assessmentPage.modules(1,3).click()
    assert.exists(assessmentPage.topicTab(1).should('have.text', 'Build In Quality Mindset'), 'User is navigated to Quality Assurance module')
    cy.fixture('QualityAssurance').then((testData) => {
      assessmentPage.parameter(1).should('be.visible').contains(testData[0].QAParameters[0])
      assessmentPage.questions(1, 2, 1).click().should('be.visible').contains(testData[0].QAQuestions[0])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(485), testData[0].notes[0])
      assessmentPage.questions(1, 2, 2).click().should('be.visible').contains(testData[0].QAQuestions[1])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(486), testData[0].notes[1])
      assessmentPage.questions(1, 2, 3).click().should('be.visible').contains(testData[0].QAQuestions[2])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(487), testData[0].notes[2])
      assessmentPage.questions(1, 2, 4).click().should('be.visible').contains(testData[0].QAQuestions[3])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(488), testData[0].notes[3])
      assessmentPage.questions(1, 2, 5).click().should('be.visible').contains(testData[0].QAQuestions[4])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(489), testData[0].notes[4])
      assessmentPage.questions(1, 2, 6).click().should('be.visible').contains(testData[0].QAQuestions[5])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(490), testData[0].notes[5])
      assessmentPage.questions(1, 2, 7).click().should('be.visible').contains(testData[0].QAQuestions[6])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(491), testData[0].notes[6])
      assessmentPage.questions(1, 2, 8).click().should('be.visible').contains(testData[0].QAQuestions[7])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(492), testData[0].notes[7])
      assessmentPage.parameterMaturityScoreDesc(1, 3).click({ multiple: true }).should('be.visible').contains(testData[0].QAAssignmentMaturityScoreDesc[0])
      assessmentPage.parameterMaturityScoreDesc(1, 4).should('be.visible').contains(testData[0].QAAssignmentMaturityScoreDesc[1])
      assessmentPage.parameterMaturityScoreDesc(1, 5).should('be.visible').contains(testData[0].QAAssignmentMaturityScoreDesc[2])
      assessmentPage.parameterMaturityScoreDesc(1, 6).should('be.visible').contains(testData[0].QAAssignmentMaturityScoreDesc[3])
      assessmentPage.parameterMaturityScoreDesc(1, 7).should('be.visible').contains(testData[0].QAAssignmentMaturityScoreDesc[4])
      assessmentPage.parameter(2).click().should('be.visible').contains(testData[0].QAParameters[1])
      assessmentPage.questions(2, 2, 1).click().should('be.visible').contains(testData[0].QAQuestions[8])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(493), testData[0].notes[0])
      assessmentPage.questions(2, 2, 2).click().should('be.visible').contains(testData[0].QAQuestions[9])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(493), testData[0].notes[0])
      assessmentPage.questions(2, 2, 3).click().should('be.visible').contains(testData[0].QAQuestions[10])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(494), testData[0].notes[0])
      assessmentPage.questions(2, 2, 4).click().should('be.visible').contains(testData[0].QAQuestions[11])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(495), testData[0].notes[0])
      assessmentPage.questions(2, 2, 5).click().should('be.visible').contains(testData[0].QAQuestions[12])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(497), testData[0].notes[0])
      assessmentPage.parameterMaturityScoreDesc(2, 3).click({ multiple: true }).should('be.visible')
      assessmentPage.parameterMaturityScoreDesc(2, 4).should('be.visible').contains(testData[0].QAAssignmentMaturityScoreDesc[6])
      assessmentPage.parameterMaturityScoreDesc(2, 5).should('be.visible').contains(testData[0].QAAssignmentMaturityScoreDesc[7])
      assessmentPage.parameterMaturityScoreDesc(2, 6).should('be.visible').contains(testData[0].QAAssignmentMaturityScoreDesc[8])
      assessmentPage.parameterMaturityScoreDesc(2, 7).should('be.visible').contains(testData[0].QAAssignmentMaturityScoreDesc[9])
      assessmentPage.editBox().should('have.length', '15')
    })
  })

  it('tc002 Test Strategy topic validation', () => {
    landingPage.assessmentNameInGrid(1).click()
    assessmentPage.modules(1,3).click()
    assessmentPage.topicTab(2).click()
    assert.exists(assessmentPage.topicTab(2).should('have.text', 'Test Strategy'), 'User is navigated to Quality Assurance module,Test strategy topic')
    cy.fixture('QualityAssurance').then((testData) => {
      assessmentPage.parameter(1).should('be.visible').contains(testData[1].TSParameters[0])
      assessmentPage.questions(1, 2, 1).should('be.visible').contains(testData[1].TSQuestions[0])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(498), testData[1].notes[0])
      assessmentPage.questions(1, 2, 2).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[1])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(499), testData[1].notes[1])
      assessmentPage.questions(1, 2, 3).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[2])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(500), testData[1].notes[2])
      assessmentPage.parameterMaturityScoreDesc(1, 3).click({ multiple: true }).should('be.visible').contains(testData[1].TSAssignmentMaturityScoreDesc[0])
      assessmentPage.parameterMaturityScoreDesc(1, 4).should('be.visible').contains(testData[1].TSAssignmentMaturityScoreDesc[1])
      assessmentPage.parameterMaturityScoreDesc(1, 5).should('be.visible').contains(testData[1].TSAssignmentMaturityScoreDesc[2])
      assessmentPage.parameterMaturityScoreDesc(1, 6).should('be.visible').contains(testData[1].TSAssignmentMaturityScoreDesc[3])
      assessmentPage.parameterMaturityScoreDesc(1, 7).should('be.visible').contains(testData[1].TSAssignmentMaturityScoreDesc[4])
      assessmentPage.parameter(2).click().should('be.visible').contains(testData[1].TSParameters[1])
      assessmentPage.questions(2, 2, 1).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[3])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(501), testData[1].notes[3])
      assessmentPage.questions(2, 2, 2).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[4])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(502), testData[1].notes[3])
      assessmentPage.questions(2, 2, 3).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[5])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(503), testData[1].notes[4])
      assessmentPage.questions(2, 2, 4).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[6])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(504), testData[1].notes[5])
      assessmentPage.questions(2, 2, 5).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[7])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(505), testData[1].notes[6])
      assessmentPage.questions(2, 2, 6).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[8])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(506), testData[1].notes[7])
      assessmentPage.questions(2, 2, 7).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[9])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(507), testData[1].notes[8])
      assessmentPage.questions(2, 2, 8).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[10])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(508), testData[1].notes[0])
      assessmentPage.questions(2, 2, 9).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[11])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(509), testData[1].notes[1])
      assessmentPage.questions(2, 2, 10).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[12])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(510), testData[1].notes[2])
      assessmentPage.questions(2, 2, 11).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[13])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(511), testData[1].notes[3])
      assessmentPage.questions(2, 2, 12).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[14])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(512), testData[1].notes[4])
      assessmentPage.questions(2, 2, 13).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[15])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(513), testData[1].notes[8])
      assessmentPage.questions(2, 2, 14).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[16])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(514), testData[1].notes[0])
      assessmentPage.questions(2, 2, 15).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[17])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(515), testData[1].notes[1])
      assessmentPage.questions(2, 2, 16).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[18])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(516), testData[1].notes[2])
      assessmentPage.questions(2, 2, 17).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[19])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(517), testData[1].notes[3])
      assessmentPage.questions(2, 2, 18).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[20])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(518), testData[1].notes[4])
      assessmentPage.questions(2, 2, 19).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[21])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(519), testData[1].notes[4])
      assessmentPage.questions(2, 2, 20).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[22])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(520), testData[1].notes[4])
      assessmentPage.questions(2, 2, 21).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[23])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(521), testData[1].notes[4])
      assessmentPage.questions(2, 2, 22).click({ multiple: true }).should('be.visible').contains(testData[1].TSQuestions[24])
      commonFunction.typeInElement(assessmentPage.notesForQuestions(522), testData[1].notes[4])
      assessmentPage.parameterMaturityScoreDesc(2, 3).click({ multiple: true }).should('be.visible')
      assessmentPage.parameterMaturityScoreDesc(2, 4).should('be.visible').contains(testData[1].TSAssignmentMaturityScoreDesc[6])
      assessmentPage.parameterMaturityScoreDesc(2, 5).should('be.visible').contains(testData[1].TSAssignmentMaturityScoreDesc[7])
      assessmentPage.parameterMaturityScoreDesc(2, 6).should('be.visible').contains(testData[1].TSAssignmentMaturityScoreDesc[8])
      assessmentPage.parameterMaturityScoreDesc(2, 7).should('be.visible').contains(testData[1].TSAssignmentMaturityScoreDesc[9])
      assessmentPage.editBox().should('have.length', '27')
    })
  })



})




